version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: user-info-service
    restart: unless-stopped
    depends_on:
        - database
    tty: true
    working_dir: /app
    expose:
      - "80"
    ports:
      - "4444:4444"
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "postgresql://user:password@user-info-service-database/userinfo"
      TEST_DATABASE_URL: "sqlite:///./test.db"
      JWK_ENDPOINT: "https://authenticate.localhost.pomerium.io/.well-known/pomerium/jwks.json"
      TEST_USER: "True"
    command: [
        "pipenv",
        "run",
        "uvicorn",
        "app.main:app",
        "--reload",
        "--host=0.0.0.0",
        "--port=80"
    ]

  #Postgres Service
  database:
    image: postgres:latest
    container_name: user-info-service-database
    restart: unless-stopped
    tty: true
    expose:
      - "5432"
    environment:
      POSTGRES_DB: userinfo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

#Docker Networks
networks:
  default:
    external:
      name: local-development-network
