"""Initial migration

Revision ID: 97f4c36233f0
Revises:
Create Date: 2021-02-17 18:36:47.569280

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97f4c36233f0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_info_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_info", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_info_id"))

    op.drop_table("user_info")
    # ### end Alembic commands ###
